Fix issue with class mediator craetion
wso2/integration-studio pull request #1244
Opened 2023-09-14 11:53 UTC by rosensilva

Fix: https://github.com/wso2/integration-studio/issues/1243

2023-09-15 08:56 UTC, SanojPunchihewa approved these changes

2023-09-15 08:58 UTC, SanojPunchihewa requested changes

2023-09-15 08:58 UTC, SanojPunchihewa commented on components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/action/ChangeRuntimeVersion.java
> +                            return "Sequence name cannot be empty";
Shouldn't this be runtime version?

2023-09-18 12:07 UTC, rosensilva commented on components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/action/ChangeRuntimeVersion.java
> +                            return "Sequence name cannot be empty";
fixed

2023-09-19 02:22 UTC, SanojPunchihewa approved these changes

2023-09-19 02:25 UTC, merged